[package]
name = "day1"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
csv = "1.3.1"
serde = { version = "1.0.215", features = ["derive"] }

[dev-dependencies]
assert2 = "0.3.15"
